// src/components/CanvasArea/templates.ts
import { Templates, Character, SpeechBubble } from "../../types";

export const templates: Templates = {
  "4koma": {
    panels: [
      { id: 1, x: 50, y: 50, width: 500, height: 170 },
      { id: 2, x: 50, y: 240, width: 500, height: 170 },
      { id: 3, x: 50, y: 430, width: 500, height: 170 },
      { id: 4, x: 50, y: 620, width: 500, height: 170 },
    ],
  },
  dialogue: {
    panels: [
      { id: 1, x: 50, y: 50, width: 500, height: 200 },
      { id: 2, x: 50, y: 270, width: 240, height: 200 },
      { id: 3, x: 310, y: 270, width: 240, height: 200 },
      { id: 4, x: 50, y: 490, width: 500, height: 260 },
    ],
  },
  action: {
    panels: [
      { id: 1, x: 50, y: 50, width: 200, height: 300 },
      { id: 2, x: 270, y: 50, width: 280, height: 180 },
      { id: 3, x: 270, y: 250, width: 280, height: 120 },
      { id: 4, x: 50, y: 370, width: 500, height: 380 },
    ],
  },
  emotional: {
    panels: [
      { id: 1, x: 50, y: 50, width: 320, height: 300 },
      { id: 2, x: 390, y: 50, width: 160, height: 140 },
      { id: 3, x: 390, y: 210, width: 160, height: 140 },
      { id: 4, x: 50, y: 370, width: 500, height: 380 },
    ],
  },
  gag: {
    panels: [
      { id: 1, x: 50, y: 50, width: 500, height: 150 },
      { id: 2, x: 50, y: 220, width: 160, height: 200 },
      { id: 3, x: 230, y: 220, width: 160, height: 200 },
      { id: 4, x: 410, y: 220, width: 140, height: 200 },
      { id: 5, x: 50, y: 440, width: 500, height: 310 },
    ],
  },
  custom: {
    panels: [
      { id: 1, x: 100, y: 100, width: 400, height: 300 },
      { id: 2, x: 100, y: 450, width: 400, height: 300 },
    ],
  },
};

// テンプレート適用時の自動配置機能
export const applyTemplateDefaults = (
  templateName: string,
  panels: any[]
): { characters: Character[], speechBubbles: SpeechBubble[] } => {
  const defaults = templateDefaults[templateName];
  
  if (!defaults || panels.length === 0) {
    console.log(`⚠️ テンプレート「${templateName}」のデフォルトが見つかりません`);
    return { characters: [], speechBubbles: [] };
  }

  console.log(`🎭 テンプレート「${templateName}」のデフォルトシーンを適用中...`);

  // キャラクター生成
  const characters: Character[] = defaults.characters.map((char, index) => ({
    ...char,
    id: `template_char_${templateName}_${Date.now()}_${index}`,
  }));

  // 吹き出し生成
  const speechBubbles: SpeechBubble[] = defaults.speechBubbles.map((bubble, index) => ({
    ...bubble,
    id: `template_bubble_${templateName}_${Date.now()}_${index}`,
  }));

  console.log(`✅ デフォルトシーン適用完了: キャラクター${characters.length}個、吹き出し${speechBubbles.length}個`);
  
  return { characters, speechBubbles };
};

// ID生成ユーティリティ
export const generateUniqueId = (prefix: string): string => {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`;
};

// テンプレート別デフォルトシーン定義
interface TemplateDefaults {
  characters: Omit<Character, "id">[];
  speechBubbles: Omit<SpeechBubble, "id">[];
}

export const templateDefaults: Record<string, TemplateDefaults> = {
  "4koma": {
    // 4コマ漫画の起承転結構成
    characters: [
      // パネル1：起（日常の導入）
      {
        panelId: 1,
        type: "hero",
        name: "主人公",
        x: 120,
        y: 140,
        scale: 2.0,
        facing: "front",
        gaze: "right",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "right",
        eyeDirection: "right",
        isGlobalPosition: true,
        bodyDirection: "right",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      {
        panelId: 1,
        type: "heroine",
        name: "ヒロイン",
        x: 430,
        y: 140,
        scale: 2.0,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      
      // パネル2：承（展開）
      {
        panelId: 2,
        type: "hero",
        name: "主人公",
        x: 300,
        y: 340,
        scale: 2.5,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "surprised",
        bodyPose: "standing",
      },
      
      // パネル3：転（盛り上がり）
      {
        panelId: 3,
        type: "heroine",
        name: "ヒロイン",
        x: 300,
        y: 530,
        scale: 2.2,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "waving",
      },
      
      // パネル4：結（オチ）
      {
        panelId: 4,
        type: "hero",
        name: "主人公",
        x: 150,
        y: 710,
        scale: 1.8,
        facing: "front",
        gaze: "right",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "right",
        eyeDirection: "down",
        isGlobalPosition: true,
        bodyDirection: "right",
        faceExpression: "embarrassed",
        bodyPose: "standing",
      },
      {
        panelId: 4,
        type: "heroine",
        name: "ヒロイン",
        x: 450,
        y: 710,
        scale: 1.8,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      // パネル1
      {
        panelId: 1,
        type: "普通",
        text: "おはよう！",
        x: 80,
        y: 90,
        scale: 1.0,
        width: 70,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 1,
        type: "普通",
        text: "おはよう",
        x: 480,
        y: 85,
        scale: 1.0,
        width: 65,
        height: 45,
        vertical: true,
        isGlobalPosition: true,
      },
      
      // パネル2
      {
        panelId: 2,
        type: "叫び",
        text: "えっ！？",
        x: 200,
        y: 280,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      
      // パネル3
      {
        panelId: 3,
        type: "普通",
        text: "そうなのよ〜",
        x: 180,
        y: 470,
        scale: 1.0,
        width: 90,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      
      // パネル4
      {
        panelId: 4,
        type: "小声",
        text: "そうだったのか...",
        x: 100,
        y: 650,
        scale: 1.0,
        width: 100,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "ふふふ",
        x: 500,
        y: 650,
        scale: 1.0,
        width: 50,
        height: 40,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },
  
  dialogue: {
    // 会話重視レイアウト
    characters: [
      // パネル1：全体ショット
      {
        panelId: 1,
        type: "hero",
        name: "主人公",
        x: 150,
        y: 170,
        scale: 1.8,
        facing: "front",
        gaze: "right",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "right",
        eyeDirection: "right",
        isGlobalPosition: true,
        bodyDirection: "right",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      {
        panelId: 1,
        type: "heroine",
        name: "ヒロイン",
        x: 400,
        y: 170,
        scale: 1.8,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      
      // パネル2：主人公アップ
      {
        panelId: 2,
        type: "hero",
        name: "主人公",
        x: 170,
        y: 380,
        scale: 2.5,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      
      // パネル3：ヒロインアップ
      {
        panelId: 3,
        type: "heroine",
        name: "ヒロイン",
        x: 430,
        y: 380,
        scale: 2.5,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "standing",
      },
      
      // パネル4：結論
      {
        panelId: 4,
        type: "hero",
        name: "主人公",
        x: 200,
        y: 630,
        scale: 2.0,
        facing: "front",
        gaze: "right",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "right",
        eyeDirection: "right",
        isGlobalPosition: true,
        bodyDirection: "right",
        faceExpression: "smile",
        bodyPose: "standing",
      },
      {
        panelId: 4,
        type: "heroine",
        name: "ヒロイン",
        x: 400,
        y: 630,
        scale: 2.0,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      {
        panelId: 1,
        type: "普通",
        text: "話があるんだ",
        x: 100,
        y: 90,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 1,
        type: "普通",
        text: "何？",
        x: 450,
        y: 85,
        scale: 1.0,
        width: 50,
        height: 40,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 2,
        type: "普通",
        text: "実は...",
        x: 110,
        y: 310,
        scale: 1.0,
        width: 70,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 3,
        type: "普通",
        text: "そうなの？",
        x: 370,
        y: 310,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "ありがとう",
        x: 150,
        y: 540,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "どういたしまして",
        x: 450,
        y: 540,
        scale: 1.0,
        width: 100,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },
  
  action: {
    // アクション系ダイナミック構成
    characters: [
      // パネル1：準備
      {
        panelId: 1,
        type: "hero",
        name: "主人公",
        x: 150,
        y: 200,
        scale: 2.2,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "fullBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      
      // パネル2：動き
      {
        panelId: 2,
        type: "hero",
        name: "主人公",
        x: 410,
        y: 140,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "walking",
      },
      
      // パネル3：アクション
      {
        panelId: 3,
        type: "hero",
        name: "主人公",
        x: 410,
        y: 310,
        scale: 1.8,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "pointing",
      },
      
      // パネル4：結果
      {
        panelId: 4,
        type: "hero",
        name: "主人公",
        x: 200,
        y: 560,
        scale: 2.5,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "waving",
      },
      {
        panelId: 4,
        type: "heroine",
        name: "ヒロイン",
        x: 400,
        y: 560,
        scale: 2.5,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      {
        panelId: 1,
        type: "心の声",
        text: "よし...",
        x: 80,
        y: 110,
        scale: 1.0,
        width: 60,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 2,
        type: "普通",
        text: "いくぞ！",
        x: 320,
        y: 80,
        scale: 1.0,
        width: 70,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 3,
        type: "叫び",
        text: "やった！",
        x: 320,
        y: 270,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "お疲れ様！",
        x: 120,
        y: 490,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "ありがとう",
        x: 480,
        y: 490,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },
  
  emotional: {
    // 感情表現重視
    characters: [
      // パネル1：メイン感情
      {
        panelId: 1,
        type: "heroine",
        name: "ヒロイン",
        x: 210,
        y: 200,
        scale: 2.5,
        facing: "front",
        gaze: "down",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "down",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "sad",
        bodyPose: "standing",
      },
      
      // パネル2：反応1
      {
        panelId: 2,
        type: "hero",
        name: "主人公",
        x: 470,
        y: 120,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "surprised",
        bodyPose: "standing",
      },
      
      // パネル3：反応2
      {
        panelId: 3,
        type: "hero",
        name: "主人公",
        x: 470,
        y: 280,
        scale: 1.8,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "worried",
        bodyPose: "thinking",
      },
      
      // パネル4：結論
      {
        panelId: 4,
        type: "heroine",
        name: "ヒロイン",
        x: 200,
        y: 560,
        scale: 2.2,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "standing",
      },
      {
        panelId: 4,
        type: "hero",
        name: "主人公",
        x: 400,
        y: 560,
        scale: 2.2,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      {
        panelId: 1,
        type: "心の声",
        text: "どうしよう...",
        x: 380,
        y: 100,
        scale: 1.0,
        width: 90,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 2,
        type: "叫び",
        text: "え！？",
        x: 420,
        y: 70,
        scale: 1.0,
        width: 60,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 3,
        type: "心の声",
        text: "何とかしないと",
        x: 420,
        y: 220,
        scale: 1.0,
        width: 100,
        height: 80,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "大丈夫だよ",
        x: 480,
        y: 490,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "普通",
        text: "ありがとう",
        x: 120,
        y: 490,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },
  
  gag: {
    // ギャグ・コメディのテンポ重視
    characters: [
      // パネル1：セットアップ
      {
        panelId: 1,
        type: "hero",
        name: "主人公",
        x: 150,
        y: 125,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      {
        panelId: 1,
        type: "heroine",
        name: "ヒロイン",
        x: 400,
        y: 125,
        scale: 2.0,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      
      // パネル2：反応1
      {
        panelId: 2,
        type: "hero",
        name: "主人公",
        x: 130,
        y: 320,
        scale: 2.3,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "surprised",
        bodyPose: "standing",
      },
      
      // パネル3：反応2
      {
        panelId: 3,
        type: "heroine",
        name: "ヒロイン",
        x: 310,
        y: 320,
        scale: 2.3,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "standing",
      },
      
      // パネル4：ツッコミ
      {
        panelId: 4,
        type: "friend",
        name: "友人",
        x: 480,
        y: 320,
        scale: 2.3,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "face",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "angry",
        bodyPose: "pointing",
      },
      
              // パネル5：オチ
      {
        panelId: 5,
        type: "hero",
        name: "主人公",
        x: 200,
        y: 600,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "down",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "embarrassed",
        bodyPose: "standing",
      },
      {
        panelId: 5,
        type: "heroine",
        name: "ヒロイン",
        x: 350,
        y: 600,
        scale: 2.0,
        facing: "front",
        gaze: "left",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "left",
        eyeDirection: "left",
        isGlobalPosition: true,
        bodyDirection: "left",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      {
        panelId: 1,
        type: "普通",
        text: "今日はいい天気だね",
        x: 100,
        y: 70,
        scale: 1.0,
        width: 100,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 1,
        type: "普通",
        text: "そうね",
        x: 450,
        y: 70,
        scale: 1.0,
        width: 50,
        height: 40,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 2,
        type: "叫び",
        text: "えー！",
        x: 80,
        y: 270,
        scale: 1.0,
        width: 60,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 3,
        type: "普通",
        text: "でも本当よ",
        x: 260,
        y: 270,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 4,
        type: "叫び",
        text: "ちょっと待て！",
        x: 430,
        y: 270,
        scale: 1.0,
        width: 90,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 5,
        type: "普通",
        text: "すみません...",
        x: 150,
        y: 530,
        scale: 1.0,
        width: 80,
        height: 60,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 5,
        type: "普通",
        text: "まあまあ",
        x: 400,
        y: 530,
        scale: 1.0,
        width: 70,
        height: 50,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },

  custom: {
    // カスタムテンプレート（シンプル構成）
    characters: [
      {
        panelId: 1,
        type: "hero",
        name: "主人公",
        x: 300,
        y: 250,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "normal",
        bodyPose: "standing",
      },
      {
        panelId: 2,
        type: "heroine",
        name: "ヒロイン",
        x: 300,
        y: 600,
        scale: 2.0,
        facing: "front",
        gaze: "center",
        pose: "standing",
        expression: "neutral",
        viewType: "halfBody",
        faceAngle: "front",
        eyeDirection: "front",
        isGlobalPosition: true,
        bodyDirection: "front",
        faceExpression: "smile",
        bodyPose: "standing",
      },
    ],
    speechBubbles: [
      {
        panelId: 1,
        type: "普通",
        text: "何か始めよう",
        x: 200,
        y: 150,
        scale: 1.0,
        width: 90,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
      {
        panelId: 2,
        type: "普通",
        text: "いいアイデアね",
        x: 200,
        y: 500,
        scale: 1.0,
        width: 100,
        height: 70,
        vertical: true,
        isGlobalPosition: true,
      },
    ],
  },
};